{
 "title": "Shaken Fist",
 "tags": [ "shakenfist" ],
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Load average",
   "type": "graph",
   "gridPos": { "h": 8, "w": 5, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "cpu_load_5", "legendFormat": "{{instance}} loadavg 5" }
   ]
  },
  {
   "title": "Instance vCPUs",
   "type": "graph",
   "gridPos": { "h": 8, "w": 5, "x": 5, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "cpu_total_instance_vcpus", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "Instance CPU time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 5, "x": 10, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(cpu_total_instance_cpu_time[5m])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "etcd All RPCs",
   "type": "graph",
   "gridPos": { "h": 8, "w": 5, "x": 15, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(grpc_server_started_total[5m]))",
     "legendFormat": "Rate"
    }
   ]
  },
  {
   "title": "Memory Max",
   "type": "graph",
   "gridPos": { "h": 7, "w": 5, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "kbytes" }
   ],
   "targets": [
    { "expr": "memory_max", "legendFormat": "{{instance}} max" }
   ]
  },
  {
   "title": "Memory Available",
   "type": "graph",
   "gridPos": { "h": 7, "w": 5, "x": 5, "y": 8 },
   "yaxes": [
    { "format": "kbytes" }
   ],
   "targets": [
    { "expr": "memory_available", "legendFormat": "{{instance}} available" }
   ]
  },
  {
   "title": "Instance memory",
   "type": "graph",
   "gridPos": { "h": 7, "w": 5, "x": 10, "y": 8 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "memory_total_instance_actual_memory",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "etcd Failed RPCs",
   "type": "graph",
   "gridPos": { "h": 8, "w": 5, "x": 15, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(grpc_server_handled_total{grpc_code!=\\\"OK\\\"}[5m])",
     "legendFormat": "Rate"
    }
   ]
  },
  {
   "title": "Disk free",
   "type": "graph",
   "gridPos": { "h": 7, "w": 5, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    { "expr": "disk_free", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "Disk read",
   "type": "graph",
   "gridPos": { "h": 7, "w": 5, "x": 5, "y": 15 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    { "expr": "rate(disk_read_bytes[5m])", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "Disk write",
   "type": "graph",
   "gridPos": { "h": 7, "w": 5, "x": 10, "y": 15 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    { "expr": "rate(disk_write_bytes[5m])", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "etcd DB Size",
   "type": "graph",
   "gridPos": { "h": 7, "w": 5, "x": 15, "y": 16 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "etcd_mvcc_db_total_size_in_bytes",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Instances total",
   "type": "graph",
   "gridPos": { "h": 7, "w": 5, "x": 0, "y": 22 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "instances_total", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "Network read",
   "type": "graph",
   "gridPos": { "h": 7, "w": 5, "x": 5, "y": 22 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    { "expr": "rate(network_read_bytes[5m])", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "Network write",
   "type": "graph",
   "gridPos": { "h": 7, "w": 5, "x": 10, "y": 22 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    { "expr": "rate(network_write_bytes[5m])", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "etcd Traffic",
   "type": "graph",
   "gridPos": { "h": 7, "w": 5, "x": 15, "y": 23 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "expr": "rate(etcd_network_client_grpc_received_bytes_total[5m])",
     "legendFormat": "{{instance}} In"
    },
    {
     "expr": "rate(etcd_network_client_grpc_sent_bytes_total[5m])",
     "legendFormat": "{{instance}} Out"
    }
   ]
  }
 ]
}